<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsUraPlugin>true</IsUraPlugin>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>2026.03.04</Version>
    <PluginInternalName>BreedersScenarioAnalyzer</PluginInternalName>
    <PluginAuthor>UmamusumeResponseAnalyzer</PluginAuthor>
    <PluginDisplayName>梦想杯剧本解析器</PluginDisplayName>
    <PluginRepositoryUrl>https://github.com/URA-Plugins/BreedersScenarioAnalyzer</PluginRepositoryUrl>
    <PluginTargets>Cygames</PluginTargets>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="i18n\Game.Designer.cs">
      <DependentUpon>Game.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="i18n\Game.resx">
      <LastGenOutput>Game.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="UmamusumeResponseAnalyzer" Version="*" PrivateAssets="all" />
  </ItemGroup>

</Project>
